{
  "id": "CVE-2020-28488",
  "sourceIdentifier": "report@snyk.io",
  "published": "2021-01-22T14:15:12.493",
  "lastModified": "2021-02-02T19:15:13.610",
  "vulnStatus": "Rejected",
  "descriptions": [
    {
      "lang": "en",
      "value": "** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: none."
    }
  ],
  "metrics": {},
  "references": []
}