{
  "id": "CVE-2024-4032",
  "sourceIdentifier": "cna@python.org",
  "published": "2024-06-17T15:15:52.517",
  "lastModified": "2024-06-17T15:15:52.517",
  "vulnStatus": "Received",
  "descriptions": [
    {
      "lang": "en",
      "value": "The \u201cipaddress\u201d module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as \u201cglobally reachable\u201d or \u201cprivate\u201d. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn\u2019t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\n\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior."
    }
  ],
  "metrics": {},
  "references": [
    {
      "url": "https://github.com/python/cpython/issues/113171",
      "source": "cna@python.org"
    },
    {
      "url": "https://github.com/python/cpython/pull/113179",
      "source": "cna@python.org"
    },
    {
      "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/",
      "source": "cna@python.org"
    },
    {
      "url": "https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml",
      "source": "cna@python.org"
    },
    {
      "url": "https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml",
      "source": "cna@python.org"
    }
  ]
}