{
  "id": "CVE-2023-26151",
  "sourceIdentifier": "report@snyk.io",
  "published": "2023-10-03T05:15:50.507",
  "lastModified": "2023-10-03T05:15:50.507",
  "vulnStatus": "Received",
  "descriptions": [
    {
      "lang": "en",
      "value": "Versions of the package asyncua before 0.9.96 are vulnerable to Denial of Service (DoS) such that an attacker can send a malformed packet and as a result, the server will enter into an infinite loop and consume excessive memory."
    }
  ],
  "metrics": {
    "cvssMetricV31": [
      {
        "source": "report@snyk.io",
        "type": "Secondary",
        "cvssData": {
          "version": "3.1",
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
          "attackVector": "NETWORK",
          "attackComplexity": "LOW",
          "privilegesRequired": "NONE",
          "userInteraction": "NONE",
          "scope": "UNCHANGED",
          "confidentialityImpact": "NONE",
          "integrityImpact": "NONE",
          "availabilityImpact": "LOW",
          "baseScore": 5.3,
          "baseSeverity": "MEDIUM"
        },
        "exploitabilityScore": 3.9,
        "impactScore": 1.4
      }
    ]
  },
  "references": [
    {
      "url": "https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8",
      "source": "report@snyk.io"
    },
    {
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/commit/f6603daa34a93a658f0e176cb0b9ee5a6643b262",
      "source": "report@snyk.io"
    },
    {
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/issues/1013",
      "source": "report@snyk.io"
    },
    {
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/pull/1039",
      "source": "report@snyk.io"
    },
    {
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/releases/tag/v0.9.96",
      "source": "report@snyk.io"
    },
    {
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709",
      "source": "report@snyk.io"
    }
  ]
}