{
  "id": "CVE-2020-35310",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2021-01-26T18:15:53.817",
  "lastModified": "2021-02-01T21:15:14.530",
  "vulnStatus": "Rejected",
  "descriptions": [
    {
      "lang": "en",
      "value": "** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none NOTE: This is disputed by the vendor; \"We have no records of contact with the original reporter, and have not been able to reproduce any issue.\""
    }
  ],
  "metrics": {},
  "references": []
}